<?php

namespace MessageBundle\Repository;

/**
 * MessageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageUserRepository extends \Doctrine\ORM\EntityRepository
{

}
