<?php

namespace MessageBundle\Repository;

/**
 * MessageTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
