<?php

namespace AppBundle\Repository;

/**
 * UserActivationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivationsRepository extends \Doctrine\ORM\EntityRepository
{
}
