<?php

namespace AuthBundle\Repository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserRoleByUserIdAndRoleId($userId, $roleId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('ur')
            ->from('AuthBundle\Entity\UserRole', 'ur')
            ->where("ur.user = $userId")
            ->andWhere("ur.role = $roleId")
            ->getQuery()
            ->getResult();
    }
}
